name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy no servidor
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          protocol: tcp4
          timeout: 120s
          debug: true
          script: |
            set -e

            cd /home/u178981784/domains/digify.com.br/digify

            echo "Commit antes:"
            git rev-parse --short HEAD

            git fetch origin main
            git reset --hard origin/main

            echo "Commit depois:"
            git rev-parse --short HEAD

            echo "Limpando caches do Laravel..."
            php artisan optimize:clear

            echo "Executando migrations..."
            php artisan migrate --force

            echo "Gerando caches do Laravel..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Deploy concluído!"